version: "3.9"

services:
  pgim:
    container_name: pgim
    gpus: all
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/pgim
    environment:
      - PYTHONPATH=/pgim
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    stdin_open: true
    tty: true
